name: Generate Podcast Feeds
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run Feed Generator
        uses: OlaHalawani/podcast-generator@main
      - name: Debugging Feed Generator
        run: |
          set -x  # Enables detailed shell debug output
          python feed.py
